---
- hosts: localhost
  become: true
  vars:
    user_list:
      - akathikar
      - cm10
      - ddesilva
      - dmutlu
      - dvahidiazar1
      - exouser
      - ghari
      - gjanson
      - jdelaterga
      - jgallio
      - mmonc
      - moelgoetz
      - nanber
      - nngu
      - oonoyona
      - rnegrini
      - tfitsum
      - tsalau
      - ubuntu
      - umair30
      - vchergarova
      - wellsaar
      - winona
      - yzhang14
      - zchyatte

- name: Adding users to docker group
  ansible.builtin.user:
    name: "{{ user_list }}"
    append: true
    groups: docker
    state: present

