# this is the base image
FROM nginx:stable-alpine
# this copies index.html into the /usr/share/nginx/html directory in the container
COPY index.html /usr/share/nginx/html/
# this tells the container to expose port 80 
EXPOSE 80